name: Validate HTML
on: [push]

jobs: 
  check-html:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: check for index.html
        run: |
          if [ -f "index.html" ]; then
            echo "index.html found"
          else
            echo "index.html not found"
            exit 1
          fi